modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "MIT" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "walkietalkie" #mandatory
version = "1.3.0" #mandatory
displayName = "Walkie-Talkie" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "walkietalkie.png" #optional
credits = "Airwan, Heimdallr-1, Kampftroll, JustinBW" #optional
authors = "Flaton" #optional
description = '''Adds walkie-talkies with different upgrades.''' #mandatory (Supports multiline text)
[[dependencies.walkietalkie]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.walkietalkie]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.walkietalkie]]
modId="voicechat"
mandatory=true
versionRange="[1.20.1-2.3.3,)"
ordering="AFTER"
side="BOTH"
[[dependencies.walkietalkie]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.13,)"
ordering = "AFTER"
side = "BOTH"
